import type {
  User,
  Appointment,
  LabResult,
  Message,
  Notification,
} from "@/types";

export const currentUser: User = {
  id: "p-001",
  email: "sarah.johnson@email.com",
  firstName: "Sarah",
  lastName: "Johnson",
  dateOfBirth: "1988-04-15",
  phone: "(555) 123-4567",
  address: "742 Evergreen Terrace, Springfield, IL 62704",
  insuranceProvider: "BlueCross BlueShield",
  insuranceId: "BCB-9923847",
};

export const appointments: Appointment[] = [
  {
    id: "a-001",
    patientId: "p-001",
    doctorName: "Dr. Emily Chen",
    doctorSpecialty: "Primary Care",
    date: "2026-03-18",
    time: "09:30",
    type: "checkup",
    status: "scheduled",
    location: "HealthPulse Main Clinic - Room 204",
    notes: "Annual wellness exam",
  },
  {
    id: "a-002",
    patientId: "p-001",
    doctorName: "Dr. James Wilson",
    doctorSpecialty: "Cardiology",
    date: "2026-03-25",
    time: "14:00",
    type: "follow-up",
    status: "scheduled",
    location: "HealthPulse Cardio Center - Room 102",
    notes: "Review stress test results",
  },
  {
    id: "a-003",
    patientId: "p-001",
    doctorName: "Dr. Emily Chen",
    doctorSpecialty: "Primary Care",
    date: "2026-02-10",
    time: "10:00",
    type: "consultation",
    status: "completed",
    location: "HealthPulse Main Clinic - Room 204",
  },
  {
    id: "a-004",
    patientId: "p-001",
    doctorName: "Dr. Lisa Park",
    doctorSpecialty: "Dermatology",
    date: "2026-01-22",
    time: "11:30",
    type: "checkup",
    status: "completed",
    location: "HealthPulse Specialists - Room 305",
  },
  {
    id: "a-005",
    patientId: "p-001",
    doctorName: "Dr. Robert Kim",
    doctorSpecialty: "Ophthalmology",
    date: "2026-04-05",
    time: "15:30",
    type: "checkup",
    status: "scheduled",
    location: "HealthPulse Vision Center",
    notes: "Annual eye exam",
  },
];

export const labResults: LabResult[] = [
  {
    id: "l-001",
    patientId: "p-001",
    testName: "Complete Blood Count (CBC)",
    category: "Hematology",
    date: "2026-03-05",
    status: "normal",
    value: "14.2",
    unit: "g/dL",
    referenceRange: "12.0 - 16.0",
    orderedBy: "Dr. Emily Chen",
  },
  {
    id: "l-002",
    patientId: "p-001",
    testName: "Hemoglobin A1C",
    category: "Metabolic",
    date: "2026-03-05",
    status: "normal",
    value: "5.4",
    unit: "%",
    referenceRange: "4.0 - 5.6",
    orderedBy: "Dr. Emily Chen",
  },
  {
    id: "l-003",
    patientId: "p-001",
    testName: "LDL Cholesterol",
    category: "Lipid Panel",
    date: "2026-03-05",
    status: "abnormal",
    value: "142",
    unit: "mg/dL",
    referenceRange: "< 100",
    orderedBy: "Dr. James Wilson",
  },
  {
    id: "l-004",
    patientId: "p-001",
    testName: "TSH",
    category: "Thyroid",
    date: "2026-02-20",
    status: "normal",
    value: "2.1",
    unit: "mIU/L",
    referenceRange: "0.4 - 4.0",
    orderedBy: "Dr. Emily Chen",
  },
  {
    id: "l-005",
    patientId: "p-001",
    testName: "Vitamin D, 25-Hydroxy",
    category: "Vitamins",
    date: "2026-02-20",
    status: "abnormal",
    value: "22",
    unit: "ng/mL",
    referenceRange: "30 - 100",
    orderedBy: "Dr. Emily Chen",
  },
  {
    id: "l-006",
    patientId: "p-001",
    testName: "Comprehensive Metabolic Panel",
    category: "Metabolic",
    date: "2026-03-12",
    status: "pending",
    value: "--",
    unit: "",
    referenceRange: "--",
    orderedBy: "Dr. Emily Chen",
  },
];

export const messages: Message[] = [
  {
    id: "m-001",
    senderId: "d-001",
    senderName: "Dr. Emily Chen",
    senderRole: "doctor",
    recipientId: "p-001",
    subject: "Lab Results Review",
    body: "Hi Sarah, I've reviewed your recent lab work. Most results look great. Your LDL cholesterol is slightly elevated at 142 mg/dL. I'd like to discuss dietary modifications and possibly starting a low-dose statin at your next visit. Your Vitamin D is also low — please start taking 2000 IU daily. Let me know if you have questions.",
    date: "2026-03-06T10:30:00",
    read: true,
    threadId: "t-001",
  },
  {
    id: "m-002",
    senderId: "p-001",
    senderName: "Sarah Johnson",
    senderRole: "patient",
    recipientId: "d-001",
    subject: "Re: Lab Results Review",
    body: "Thank you Dr. Chen. I'll pick up the Vitamin D supplements today. Regarding the cholesterol, are there specific dietary changes you'd recommend before we consider medication?",
    date: "2026-03-06T14:15:00",
    read: true,
    threadId: "t-001",
  },
  {
    id: "m-003",
    senderId: "d-002",
    senderName: "Dr. James Wilson",
    senderRole: "doctor",
    recipientId: "p-001",
    subject: "Upcoming Cardiology Appointment",
    body: "Hello Sarah, just a reminder about your follow-up appointment on March 25th. Please avoid caffeine for 24 hours before your visit as we may run an additional ECG. Bring a list of any current medications.",
    date: "2026-03-10T09:00:00",
    read: false,
    threadId: "t-002",
  },
  {
    id: "m-004",
    senderId: "n-001",
    senderName: "Nurse Maria Garcia",
    senderRole: "nurse",
    recipientId: "p-001",
    subject: "Prescription Refill Confirmation",
    body: "Hi Sarah, your prescription for Lisinopril 10mg has been refilled and sent to your pharmacy (CVS on Main St). It should be ready for pickup by end of day today.",
    date: "2026-03-12T16:45:00",
    read: false,
    threadId: "t-003",
  },
];

export const notifications: Notification[] = [
  {
    id: "n-001",
    type: "appointment",
    title: "Upcoming Appointment",
    description:
      "Appointment with Dr. Emily Chen on March 18 at 9:30 AM",
    date: "2026-03-14T08:00:00",
    read: false,
  },
  {
    id: "n-002",
    type: "lab",
    title: "Lab Results Available",
    description: "Comprehensive Metabolic Panel results are pending",
    date: "2026-03-12T12:00:00",
    read: false,
  },
  {
    id: "n-003",
    type: "message",
    title: "New Message",
    description: "Dr. James Wilson sent you a message about your appointment",
    date: "2026-03-10T09:00:00",
    read: true,
  },
  {
    id: "n-004",
    type: "billing",
    title: "Insurance Claim Processed",
    description: "Claim for Feb 10 visit has been processed by BlueCross",
    date: "2026-03-08T15:30:00",
    read: true,
  },
];
